### PR TITLE
Add Numpy x.x

### PR DESCRIPTION
**Pull request by 183amir**
Since we are linking against Numpy.

### CODE REVIEW

**Comment by 183amir** [comment]
@jakirkham ok, then.

**Comment by jakirkham** [comment]
Also, not that this is a problem, but there is no need to do `[skip appveyor]` any more. We automatically disable it on the feedstock if `skip: true  # [win]` is in the recipe. This should only be needed for the `staged-recipes` repo.

**Comment by 183amir** [comment]
Thanks, I didn't notice.

**Comment by jakirkham** [comment]
No worries. It isn't exactly obvious.

**Comment by jakirkham** [comment]
LGTM. Everything seems to be doing the right thing.

Feel free to ignore the Travis CI push failing status. This seems to be a holdover from when it was a branch on this repo.

Merge when you are ready.

**Pull request merged**
