### PR TITLE
Add Numpy x.x

### PR DESCRIPTION
**Pull request by 183amir**
Since we are linking against Numpy.

### CODE REVIEW

**Comment by 183amir** [comment]
@jakirkham Thank you for reminding me.

**Comment by jakirkham** [comment]
Oh, so you will want to do this on your fork otherwise it will deploy to conda-forge. Just cancel the builds so this doesn't happen.

**Comment by 183amir** [comment]
I cannot cancel this on travis.

**Comment by jakirkham** [comment]
Go to your Travis CI account and press the refresh/sync button.

**Comment by 183amir** [comment]
Ok. My account was not synced with Github. I cancelled it.

**Comment by jakirkham** [comment]
Excellent. Sorry for the excitement.

**Comment by 183amir** [comment]
So should I do this on my fork again?

**Comment by jakirkham** [comment]
Yes please. We can close this PR too.

**Pull request closed without merging**
