### PR TITLE
Pin boost

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by jakirkham** [comment]
Seems we are having some troubles here, but it may be caused by changes we have made in terms of handling BLAS dependent packages. We should modernize your stack @183amir. Could you please remind which things are BLAS dependent?

**Comment by jakirkham** [comment]
Moral of the story, @183amir, just follow along with what we have done with NumPy as can be seen [here](https://github.com/conda-forge/numpy-feedstock/blob/d21e1f3a06e492d2ae6172ec2ce2d8bcfe77b4b5/recipe/meta.yaml). Anything that says `blas` you need. Also, anything that says variant you need. Put your best attempt at this in a PR and ping me. We will go from there.

**Comment by 183amir** [comment]
@jakirkham only `bob.math` links against `blas`.

**Comment by jakirkham** [comment]
Right, which is why we need to update this. We just provided BLAS support in conda-forge. It happened at the same time as this Boost update was proposed. So, you are in a special situation as both affect `bob.math`. In any event, I think this will be easy to fix. It is pretty much a copy-and-paste job. Just follow the NumPy recipe linked above.

**Pull request closed without merging**
